Upgrade scripts to latest functions

diff --git a/kfc b/kfc
--- a/kfc
+++ b/kfc
@@ -8,7 +8,14 @@ DEFAULT_ADDRESS=127.0.0.1
 
 usage() {
     cat <<END
-Execute a command with a kube port forward.
+Execute a command with a kube port forward (use local port 0 for ephemeral).
+
+Following environment variables are available for the executed command:
+
+  KFC_REMOTE_TARGET (target pod)
+  KFC_REMOTE_PORT (remote target pod port number)
+  KFC_LOCAL_PORT (local listening port number)
+  KFC_LOCAL_ADDRESS (local bind address)
 
 Usage:
   $0 [options] <target pod> <port mapping> <command> [<arg> ...]
@@ -17,7 +24,7 @@ Options:
   --context, -c <STRING>
     Name of the Kubernetes context
   --namespace, -n <IDENTIFIER>
-    Namespace of target pod
+    Namespace of target pod resource
   --address, -a <NETADDR>
     Listen address to expose port ($DEFAULT_ADDRESS)
   --help, -h
@@ -73,16 +80,18 @@ args=()
 remote_port=${port##*:}
 local_port=${port%%:*}
 
+[[ $local_port && $local_port -eq 0 ]] && ephemeral_port && local_port=$EPHEMERAL_PORT
+
 [[ $local_port ]] || local_port=$remote_port
 
-valid_int "$remote_port" || error "Invalid number for remote port argument"
-valid_int "$local_port" || error "Invalid number for local port argument"
+valid_uint "$remote_port" || error "Invalid number for remote port argument"
+valid_uint "$local_port" || error "Invalid number for local port argument"
 
-exec_job kubectl "${args[@]}" port-forward --address "$address" "$pod" "$local_port:$remote_port" >/dev/null
+job:run - kubectl "${args[@]}" port-forward --address "$address" "$pod" "$local_port:$remote_port" >/dev/null
 
 until nc -z "$address" "$local_port"; do sleep .1; done
 
-export KFC_REMOTE_POD=$pod
+export KFC_REMOTE_TARGET=$pod
 export KFC_REMOTE_PORT=$remote_port
 export KFC_LOCAL_PORT=$local_port
 export KFC_LOCAL_ADDRESS=$address
diff --git a/ksu b/ksu
--- a/ksu
+++ b/ksu
@@ -4,41 +4,24 @@ set -e
 
 . functions
 
-KSU_IMAGE=${KSU_IMAGE:-debian}
+KSU_IMAGE=${KSU_IMAGE:-alpine}
 
-usage() {
+function usage {
     cat <<END
-Run a priviledged pod on a Kubernetes node.
+Spawn super user priviledged pod on a target node.
 
 Usage:
-  $0 [options] <node> <mount>
+  $0 <node> [<namespace>]
 
 Options:
-  --context, -c <STRING>
-    Name of the Kubernetes context
-  --namespace, -n <IDENTIFIER>
-    Namespace for the pod
   --help, -h
     Display this help
 END
     exit 2
 }
 
-context=
-namespace=
-node=
-mount=
-
 while [[ $# -gt 0 ]]; do
 case $1 in
---context | -c)
-    context=$2
-    shift 2 || usage
-    ;;
---namespace | -n)
-    namespace=$2
-    shift 2 || usage
-    ;;
 --help | -h)
     usage
     ;;
@@ -55,50 +38,32 @@ case $1 in
 esac
 done
 
-node=$1
-shift || usage
+[[ $# -ge 1 && $# -le 2 ]] || usage
 
-valid_identifier "$node" || error "Invalid node name"
 
-mount=$1
-shift || usage
+node=$1 namespace=$2
 
-args=()
-[[ $context ]] && args+=(--context "$context")
-[[ $namespace ]] && args+=(--namespace "$namespace")
+[[ $(kubectl get node "$node" --ignore-not-found) ]] || error "Node not found"
 
 pod_overrides=$(cat <<END
 {"spec":{
   "nodeName": "$node",
   "hostPID": true,
   "hostNetwork": true,
-  "tolerations": [{"operator": "Exists"}],
   "containers":[{
-    "name": "debug",
-    "image": $(jquote "$KSU_IMAGE"),
-    "workingDir": "/ksu",
-    "command": ["bash"],
-    "securityContext": {"privileged": true},
+    "name":"debug",
+    "image":"$KSU_IMAGE",
+    "command": ["nsenter", "--mount=/proc/1/ns/mnt", "--ipc=/proc/1/ns/ipc", "--uts=/proc/1/ns/uts", "--", "bash"],
     "stdin": true,
     "tty": true,
-    "volumeMounts": [{
-        "name": "mount",
-        "mountPath": "/ksu"
-    }]
+    "securityContext": {"privileged": true}
   }],
-  "volumes":[{
-      "name": "mount",
-      "hostPath":{
-        "path": $(jquote "$path")
-      }
-  }]
+  "automountServiceAccountToken": false,
+  "tolerations": [{"operator": "Exists"}]
 }}
 END
 )
 
-instance_name=$(cat /proc/sys/kernel/random/uuid)
-pod_name=ksu-$instance_name
-
-kubectl "${args[@]}" run $pod_name -it --quiet --restart=Never --rm --image "$KSU_IMAGE" \
-  --labels kind=debug,name=ksu,instance=$instance_name,user="$USER" \
+kubectl -n "$namespace" run ksu -it --quiet --restart=Never --rm --image "$KSU_IMAGE" \
+  --labels "owner=$USER,kind=debug" \
   --overrides "$pod_overrides"
diff --git a/list-pod-creation b/list-pod-creation
--- a/list-pod-creation
+++ b/list-pod-creation
@@ -75,7 +75,7 @@ done
 
 since=0
 if [[ $period ]]; then
-    since=$(parse_duration "$period") || error "Invalid since time period duration"
+    duration: since "$period" || error "Invalid since time period duration"
 fi
 
 kubectl $context_arg get $namespace_arg "${selectors_arg[@]}" pods -o json | jq -r '[.items[] | .metadata | select($since == 0 or now - (.creationTimestamp | fromdate) < $since)] | sort_by(.creationTimestamp) | reverse | .[] | .creationTimestamp + " " + .namespace + " " + .name' --argjson since $since
