Make sure 'kfc' command exit in error when port forward fails to start

diff --git a/kfc b/kfc
--- a/kfc
+++ b/kfc
@@ -87,9 +87,17 @@ local_port=${port%%:*}
 valid_uint "$remote_port" || error "Invalid number for remote port argument"
 valid_uint "$local_port" || error "Invalid number for local port argument"
 
+require_command nc
+
 job:run - kubectl "${args[@]}" port-forward --address "$address" "$pod" "$local_port:$remote_port" >/dev/null
 
-until nc -z "$address" "$local_port"; do sleep .1; done
+pid=$!
+
+until nc -z "$address" "$local_port"; do
+	sleep .1
+
+	kill -0 $pid 2>/dev/null || error "Failed running port forward"
+done
 
 export KFC_REMOTE_TARGET=$pod
 export KFC_REMOTE_PORT=$remote_port
