Convert space indentation to tabs

diff --git a/list-pod-creation b/list-pod-creation
--- a/list-pod-creation
+++ b/list-pod-creation
@@ -5,7 +5,7 @@ set -e
 . functions
 
 function usage {
-    cat <<END
+	cat <<END
 List pods with their creation time with most recent first.
 
 Usage:
@@ -23,7 +23,7 @@ Options:
   --help, -h
     Display this help
 END
-    exit 2
+	exit 2
 }
 
 context=
@@ -34,48 +34,48 @@ period=
 while [[ $# -gt 0 ]]; do
 case $1 in
 --context | -c)
-    context=$2
-    shift 2 || usage
-    ;;
+	context=$2
+	shift 2 || usage
+	;;
 --namespace | -n)
-    namespace=$2
-    shift 2 || usage
-    ;;
+	namespace=$2
+	shift 2 || usage
+	;;
 --selector | -l)
-    selectors+=("$2")
-    shift 2 || usage
-    ;;
+	selectors+=("$2")
+	shift 2 || usage
+	;;
 --since | -t)
-    period=$2
-    shift 2 || usage
-    ;;
+	period=$2
+	shift 2 || usage
+	;;
 --help | -h)
-    usage
-    ;;
+	usage
+	;;
 *)
-    error "Unexpected argument: $1"
-    ;;
+	error "Unexpected argument: $1"
+	;;
 esac
 done
 
 context_arg=
 if [[ $context ]]; then
-    context_arg=--context=$context
+	context_arg=--context=$context
 fi
 
 namespace_arg=--all-namespaces
 if [[ $namespace ]]; then
-    namespace_arg=--namespace=$namespace
+	namespace_arg=--namespace=$namespace
 fi
 
 selectors_arg=()
 for selector in  "${selectors[@]}"; do
-    selectors_arg+=("--selector=$selector")
+	selectors_arg+=("--selector=$selector")
 done
 
 since=0
 if [[ $period ]]; then
-    duration: since "$period" || error "Invalid since time period duration"
+	duration: since "$period" || error "Invalid since time period duration"
 fi
 
 kubectl $context_arg get $namespace_arg "${selectors_arg[@]}" pods -o json | jq -r '[.items[] | .metadata | select($since == 0 or now - (.creationTimestamp | fromdate) < $since)] | sort_by(.creationTimestamp) | reverse | .[] | .creationTimestamp + " " + .namespace + " " + .name' --argjson since $since
diff --git a/tcpdump-pod b/tcpdump-pod
--- a/tcpdump-pod
+++ b/tcpdump-pod
@@ -5,7 +5,7 @@ set -e
 . functions
 
 usage() {
-    cat <<END
+	cat <<END
 Run a TCP dump on a pod.
 
 Usage:
@@ -21,7 +21,7 @@ Options:
   --help, -h
     Display this help
 END
-    exit 2
+	exit 2
 }
 
 context=
@@ -32,30 +32,30 @@ proxy=
 while [[ $# -gt 0 ]]; do
 case $1 in
 --context | -c)
-    context=$2
-    shift 2 || usage
-    ;;
+	context=$2
+	shift 2 || usage
+	;;
 --namespace | -n)
-    namespace=$2
-    shift 2 || usage
-    ;;
+	namespace=$2
+	shift 2 || usage
+	;;
 --proxy | -p)
-    proxy=proxy
-    shift
-    ;;
+	proxy=proxy
+	shift
+	;;
 --help | -h)
-    usage
-    ;;
+	usage
+	;;
 --)
-    shift
-    break
-    ;;
+	shift
+	break
+	;;
 -*)
-    error "Unknown option: $1"
-    ;;
+	error "Unknown option: $1"
+	;;
 *)
-    break
-    ;;
+	break
+	;;
 esac
 done
 
@@ -68,9 +68,9 @@ kubectl_args=()
 exec_kubectl() { kubectl "${kubectl_args[@]}" "$@"; }
 
 if [[ ! $pod ]]; then
-    pod=$(exec_kubectl get pod -o name | xargs -r basename -a | fzf --tac) || error "No pod selected"
+	pod=$(exec_kubectl get pod -o name | xargs -r basename -a | fzf --tac) || error "No pod selected"
 else
-    [[ $(exec_kubectl get pod "$pod" -o name --ignore-not-found) ]] || error "Pod not found: $pod"
+	[[ $(exec_kubectl get pod "$pod" -o name --ignore-not-found) ]] || error "Pod not found: $pod"
 fi
 
 [[ $namespace ]] || namespace=$(exec_kubectl get pod "$pod" --template {{.metadata.namespace}})
@@ -81,42 +81,42 @@ snooper_pod="tcpdump-$RANDOM"
 
 snooper_pod_env='[]'
 if [[ $proxy ]]; then
-    snooper_pod_env='[
-        {"name": "http_proxy", "value": "'"$http_proxy"'"},
-        {"name": "https_proxy", "value": "'"$https_proxy"'"},
-        {"name": "no_proxy", "value": "'"$no_proxy"'"}
-    ]'
+	snooper_pod_env='[
+		{"name": "http_proxy", "value": "'"$http_proxy"'"},
+		{"name": "https_proxy", "value": "'"$https_proxy"'"},
+		{"name": "no_proxy", "value": "'"$no_proxy"'"}
+	]'
 fi
 
 snooper_pod_overrides='{"spec":{
-  "nodeName": "'$node'",
-  "hostPID": true,
-  "hostNetwork": true,
-  "tolerations": [{"operator": "Exists"}],
-  "containers":[{
-    "name": "snooper",
-    "image": "debian",
-    "command":["bash", "-c", "apt-get update && apt-get install iproute2 tcpdump docker.io -yq --no-install-recommends && touch /ready && sleep 3600"],
-    "env": '"$snooper_pod_env",'
-    "securityContext": {"privileged": true},
-    "volumeMounts":[{
-      "name": "dockersocket",
-      "mountPath": "/var/run/docker.sock"
-    }]
-  }],
-  "volumes":[{
-      "name": "dockersocket",
-      "hostPath":{
-        "path": "/var/run/docker.sock"
-      }
-    }]
+	"nodeName": "'$node'",
+	"hostPID": true,
+	"hostNetwork": true,
+	"tolerations": [{"operator": "Exists"}],
+	"containers":[{
+		"name": "snooper",
+		"image": "debian",
+		"command":["bash", "-c", "apt-get update && apt-get install iproute2 tcpdump docker.io -yq --no-install-recommends && touch /ready && sleep 3600"],
+		"env": '"$snooper_pod_env",'
+		"securityContext": {"privileged": true},
+		"volumeMounts":[{
+			"name": "dockersocket",
+			"mountPath": "/var/run/docker.sock"
+		}]
+	}],
+	"volumes":[{
+		"name": "dockersocket",
+		"hostPath":{
+			"path": "/var/run/docker.sock"
+		}
+	}]
 }}'
 
 msg "Creating snooper pod" @green@ $snooper_pod "on target pod node" @green@ $node
 
 exec_kubectl run "$snooper_pod" --image debian --restart=Never \
-    --labels "kind=debug,owner=$USER,pod=$pod" \
-    --overrides "$snooper_pod_overrides"
+	--labels "kind=debug,owner=$USER,pod=$pod" \
+	--overrides "$snooper_pod_overrides"
 
 tmp_file; dump_script=$TMP_FILE
 
diff --git a/test-logger b/test-logger
--- a/test-logger
+++ b/test-logger
@@ -7,7 +7,7 @@ set -e
 SELECTOR=app.kubernetes.io/name=test-logger,app.kubernetes.io/instance
 
 function usage {
-    cat <<END
+	cat <<END
 Manage test loggers.
 
 Usage:
@@ -22,7 +22,7 @@ Options:
   --help, -h
     Display this help
 END
-    exit 2
+	exit 2
 }
 
 declare -A CMD=()
@@ -30,21 +30,21 @@ declare -A CMD=()
 declare -A ENTRY=()
 
 function set_entry {
-    local namespace= name=$1
+	local namespace= name=$1
 
-    if [[ $name == */* ]]; then
-        namespace=${name%%/*}
-        name=${name:${#namespace}+1}
-    fi
+	if [[ $name == */* ]]; then
+		namespace=${name%%/*}
+		name=${name:${#namespace}+1}
+	fi
 
-    valid_identifier "$name" || error "Invalid name identifier: $name"
-    [[ ! $namespace ]] || valid_identifier "$namespace" || error "Invalid namespace identifier: $namespace"
+	valid_identifier "$name" || error "Invalid name identifier: $name"
+	[[ ! $namespace ]] || valid_identifier "$namespace" || error "Invalid namespace identifier: $namespace"
 
-    ENTRY=([namespace]=$namespace [name]=$name)
+	ENTRY=([namespace]=$namespace [name]=$name)
 }
 
 function kubectl_entry {
-    kubectl -n "${ENTRY[namespace]}" -l "$SELECTOR=${ENTRY[name]}" "$@"
+	kubectl -n "${ENTRY[namespace]}" -l "$SELECTOR=${ENTRY[name]}" "$@"
 }
 
 require_command jq
@@ -55,63 +55,63 @@ annotations=()
 while [[ $# -gt 0 ]]; do
 case $1 in
 --labels | -l)
-    push labels "$2"
-    shift 2 || usage
-    ;;
+	push labels "$2"
+	shift 2 || usage
+	;;
 --annotations | -a)
-    push annotations "$2"
-    shift 2 || usage
-    ;;
+	push annotations "$2"
+	shift 2 || usage
+	;;
 --help | -h)
-    usage
-    ;;
+	usage
+	;;
 --)
-    shift
-    break
-    ;;
+	shift
+	break
+	;;
 -*)
-    error "Unknown option: $1"
-    ;;
+	error "Unknown option: $1"
+	;;
 *)
-    break
-    ;;
+	break
+	;;
 esac
 done
 
 CMD[start]=_; __start() {
-    local namespace
-    namespace=$(kubectl_entry get po -o jsonpath={.items[*].metadata.namespace} | head)
+	local namespace
+	namespace=$(kubectl_entry get po -o jsonpath={.items[*].metadata.namespace} | head)
 
-    [[ $namespace ]] && error "Test logger exists: $namespace/${ENTRY[name]}"
+	[[ $namespace ]] && error "Test logger exists: $namespace/${ENTRY[name]}"
 
-    kubectl_entry run test-logger-${ENTRY[name]} --quiet --image bash "$@" \
-        --labels=$(concat , "${labels[@]}" "$SELECTOR=${ENTRY[name]}") \
-        --annotations=$(concat , "${annotations[@]}") \
-        -- bash -c 'tail -q -F test.log 2> /dev/null' >/dev/null
+	kubectl_entry run test-logger-${ENTRY[name]} --quiet --image bash "$@" \
+		--labels=$(concat , "${labels[@]}" "$SELECTOR=${ENTRY[name]}") \
+		--annotations=$(concat , "${annotations[@]}") \
+		-- bash -c 'tail -q -F test.log 2> /dev/null' >/dev/null
 }
 
 CMD[list]=_; __list() {
-    echo "${ENTRY[namespace]}/${ENTRY[name]}"
+	echo "${ENTRY[namespace]}/${ENTRY[name]}"
 }
 
 CMD[send]=_; __send() {
-    if [[ ! ${CMD[send_read]} ]]; then
-        CMD[send_read]=_
-        CMD[send_data]=$(cat)
-    fi
+	if [[ ! ${CMD[send_read]} ]]; then
+		CMD[send_read]=_
+		CMD[send_data]=$(cat)
+	fi
 
-    local pod
-    for pod in $(kubectl_entry get po -o name | xargs -r basename -a); do
-        <<< "${CMD[send_data]}" kubectl exec -i -n "${ENTRY[namespace]}" $pod -- bash -c 'cat >> test.log'
-    done
+	local pod
+	for pod in $(kubectl_entry get po -o name | xargs -r basename -a); do
+		<<< "${CMD[send_data]}" kubectl exec -i -n "${ENTRY[namespace]}" $pod -- bash -c 'cat >> test.log'
+	done
 }
 
 CMD[logs]=_; __logs() {
-    kubectl_entry logs --tail=-1
+	kubectl_entry logs --tail=-1
 }
 
 CMD[stop]=_; __stop() {
-    kubectl_entry delete po --grace-period 1 >/dev/null
+	kubectl_entry delete po --grace-period 1 >/dev/null
 }
 
 cmd=$1
@@ -120,41 +120,41 @@ shift && [[ $cmd ]] || usage
 [[ ${CMD[$cmd]} ]] || usage
 
 if [[ $cmd == start ]]; then
-    entries=("$1")
-    shift || usage
+	entries=("$1")
+	shift || usage
 else
-    data=$(kubectl get -A po -l "$SELECTOR" -o json)
+	data=$(kubectl get -A po -l "$SELECTOR" -o json)
 
-    entries=($(<<< "$data" jq -r '.items[].metadata | [.namespace, .labels["app.kubernetes.io/instance"]] | join("/")'))
+	entries=($(<<< "$data" jq -r '.items[].metadata | [.namespace, .labels["app.kubernetes.io/instance"]] | join("/")'))
 
-    if [[ $# -gt 0 ]]; then
-        declare -A selected=()
+	if [[ $# -gt 0 ]]; then
+		declare -A selected=()
 
-        while [[ $# -gt 0 ]]; do
-            selector=$1 && shift
+		while [[ $# -gt 0 ]]; do
+			selector=$1 && shift
 
-            found=
-            for entry in "${entries[@]}"; do
-                set_entry "$entry"
+			found=
+			for entry in "${entries[@]}"; do
+				set_entry "$entry"
 
-                [[ $selector == ${ENTRY[namespace]}/${ENTRY[name]} ]] || \
-                [[ $selector == ${ENTRY[namespace]}/ ]] || \
-                [[ $selector == ${ENTRY[name]} ]] || \
-                continue
+				[[ $selector == ${ENTRY[namespace]}/${ENTRY[name]} ]] || \
+				[[ $selector == ${ENTRY[namespace]}/ ]] || \
+				[[ $selector == ${ENTRY[name]} ]] || \
+				continue
 
-                selected[$entry]=_
+				selected[$entry]=_
 
-                found=_
-            done
-            [[ $found ]] || error "No test logger matching: $selector"
-        done
+				found=_
+			done
+			[[ $found ]] || error "No test logger matching: $selector"
+		done
 
-        _filter() { [[ ${selected[$1]} ]]; }; filter:: entries +@ _filter
-    fi
+		_filter() { [[ ${selected[$1]} ]]; }; filter:: entries +@ _filter
+	fi
 fi
 
 for entry in "${entries[@]}"; do
-    set_entry "$entry"
+	set_entry "$entry"
 
-    __$cmd "$@"
+	__$cmd "$@"
 done
